/*FUNÇOES NUMÉRICAS*/

/*MOSTRA O PROXIMO NUMERO INTEIRO*/
SELECT CEILING(12.33333333) AS RESULTADO;

/*MOSTRA O ANTERIOR NUMERO INTEIRO*/
SELECT ROUND(12.33333333) AS RESULTADO;

/*ARREDONDAR*/
SELECT FLOOR(12.33333333) AS RESULTADO;

/*RAÍZ QUADRADO*/
SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO, 3) AS FATURAMENTO
FROM ITENS_NOTAS_FISCAIS;

/* Na tabela de notas fiscais temos o valor do imposto. 
Já na tabela de itens temos a quantidade e o faturamento. 
Calcule o valor do imposto pago no ano de 2016 arredondando para o menor inteiro. */

SELECT YEAR(DATA_VENDA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);
